version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "3001:5432"
  web:
    build: ./web
    command: bash -c "rails db:migrate"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./web:/shoe-shop
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
