development:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: shoe-shop_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:c552483301a855ff4e9589ed2bc0b41b@porgy.redistogo.com:11491/
  channel_prefix: shoe-shop_production
